### ISSUE TITLE
Suggestion : import `variables.css` file in css

### ISSUE THREAD

**Issue by romainmenke** [penpen-365/vite_practice1#1]
Here you have a list of regular `@import` rules.

https://github.com/penpen-365/vite_practice1/blob/f14cac4281d27e9782b71cbf0573dd654e253605/src/assets/css/style.css#L4-L6

Is it possible to also add `variables.css` here as an `@import` statement?

That would become :

```css
 @import url("/assets/css/vendor/_sanitize.css"); 
 @import url("/assets/css/data/_variables.css"); 
 @import url("/assets/css/global/_base.css"); 
 @import url("/assets/css/global/_stracture.css");
```

Or did you need to use `postcss-global-data` to resolve a specific issue?

**Comment by penpen-365** [comment]
Yes, and fixed this point! Thank you for your kindness.
