### ISSUE TITLE
Suggestion : do not transpile CSS custom properties

### ISSUE THREAD

**Issue by romainmenke** [penpen-365/vite_practice1#2]
https://github.com/penpen-365/vite_practice1/blob/f14cac4281d27e9782b71cbf0573dd654e253605/postcss.config.js#L21-L23

All browsers support CSS custom properties and have done so for a very long time :)

It is better to remove this plugin unless you need to support very old browser versions.

**Comment by penpen-365** [comment]
I was concerned about the browser performance and readability of web dev tools.
However, I agree to change the config is better and I fixed it! Thank you for pointing it out :D
